version: "3"
services:
  python_app:
    build: ./app_info
    container_name: code
    restart: always
    ports:
      - 5000:5000
    command: python3 code.py

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    #network_mode: host
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    
    

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    #network_mode: host
    ports:
      - 3000:3000
    environment:
     - GF_SECURITY_ADMIN_PASSWORD=grafana
    depends_on:
      - prometheus
    volumes:
      - './grafana.ini:/etc/grafana/grafana.ini'